#!/bin/sh

CWD="$(dirname "$0")"
. $CWD/funcs.sh

[ -d "$BASEDIR/images" ] || die "no images directory found"
[ -d "$BASEDIR/mount" ] || mkdir -p "$BASEDIR/mount"

_which kpartx >/dev/null
kpartx=`kpartx -asv $BASEDIR/images/*.img` || die "Could not setup loop-back access to $BASEDIR/images/*.img"
img_boot_dev=`echo "$kpartx" | grep -o 'loop.p.' | head -1 | tail -1`
img_root_dev=`echo "$kpartx" | grep -o 'loop.p.' | head -2 | tail -1`

test "$img_boot_dev" -a "$img_root_dev" || die "Could not extract boot and root loop device from kpartx output: $NL$kpartx"
img_boot_dev=/dev/mapper/$img_boot_dev
img_root_dev=/dev/mapper/$img_root_dev
mkdir -p $BASEDIR/mount/img_root
mount -t ext4 $img_root_dev $BASEDIR/mount/img_root || die "Could not mount $img_root_dev $BASEDIR/mount/img_root"
mkdir -p $BASEDIR/mount/img_root/boot || die "Could not mkdir $BASEDIR/mount/img_root/boot"
mount -t vfat $img_boot_dev $BASEDIR/mount/img_root/boot || die "Could not mount $img_boot_dev $BASEDIR/mount/img_root/boot"
cp -a "`_which qemu-arm-static`" $BASEDIR/mount/img_root/usr/bin/ || die "Could not copy qemu-arm-static"

exit 0
