#!/bin/sh

. `readlink -f "$0.conf"`

CWD="$(dirname "$0")"
. `readlink -f "$CWD/rpi-funcs.sh"`

# download if missing
rpi_init || die "init failed"

# mount image file and copy static files
rpi_mount || die "mount failed"

copyToPi /etc/default/keyboard
copyToPi /etc/default/console-setup
copyToPi /etc/resolv.conf
copyToPi /etc/localtime

rpi_chroot_setup || die "chroot-setup failed"
trap rpi_chroot_teardown EXIT

# cat $CWD/run_in_chroot.sh | chroot $BASEDIR/mount/img_root /bin/sh || die "chroot failed"
### instead of doing stuff via sh scripts we could use ansible
ansible-playbook -c chroot -i "$BASEDIR/mount/img_root," ansible/playbook.yml

rpi_chroot_teardown || die "chroot-teardown failed"
trap '' EXIT

# write to sdcard
rpi_mksdcard || die "mksdcard failed"

# umount
rpi_umount || die "umount failed"

