#!/bin/sh

CONFIGFILE=rpi-image-creator.conf

rpi-init $CONFIGFILE

# mount image file and copy static files
rpi-mount $CONFIGFILE

cat run_in_chroot.sh | rpi-chroot $CONFIGFILE /bin/sh

### instead of doing stuff via sh scripts we could use ansible
# sudo ansible-playbook -c chroot -i '/path/to/debootstrap,/path/to/debootstrap' my-cool-playbook.yml

# write to sdcard
### rpi-mksdcard $CONFIGFILE

# umount
rpi-umount $CONFIGFILE

